minimum_pre_commit_version: "4.3.0"
default_language_version:
  python: python3.12

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-yaml
    - id: check-json
    - id: detect-private-key
    - id: check-added-large-files
      args: ["--maxkb=1000"]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.10
  hooks:
    - id: ruff
      args: ["--fix", "--exit-non-zero-on-fix", "--config", "./pyproject.toml"]
    - id: ruff-format
      args: ["--config", "./pyproject.toml"]

- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
    - id: codespell
      args: ["--ignore-words-list", "te,fo"]
